### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by XiroInfinity** [aclich/Holocure_save_editor#4]
Please explain?

![HSE virus report](https://user-images.githubusercontent.com/8839880/177024052-49893672-dd63-4a23-a433-60bb04f75175.png)

**Comment by aclich** [comment]
The exe is packed with pyinstaller from the source code in repository. You have right to not use it if you have any concern or just run from source code.

**Comment by XiroInfinity** [comment]
> 

Okay, but this is normal for windows to alert people to?

**Comment by aclich** [comment]
Well, yes for windows. It's particular a false positive in windows defender on pyinstaller exes. But it's wired that my 3 different PC with w10 and w11 did not detected out the virus. Anyway, thanks for your report on this issue, I'll try to fixed it and release another exe.
Some reference: https://python.plainenglish.io/pyinstaller-exe-false-positive-trojan-virus-resolved-b33842bd3184

**Comment by XiroInfinity** [comment]
I understand. Thank you for the explanation, and keep up the good work.

**Comment by aclich** [comment]
### Update
This is my full explanation of the virus issue on released exe. And it is a **false positive**, don't worry if you downloaded or used it.
First, I will explain how does the exe come from.
Since this project is written in python, users will need a python interpreter to execute it, but windows do not include any of that in default. So, if the python developer wants to make their code portable and with executable files, the [**pyinstaller**](https://pyinstaller.org/en/stable/index.html) is here to help. Simply put, it will pack a python interpreter and dependencies together in a single build. (It is also why this simple app so big.) However, the exe packed by pyinstaller usually triggers some false positive in anti-virus software since it contains some "virus-like" behavior, ex: running-compression, self-extraction...etc.
Last, if you want to use this tool, please go ahead since it's not harmful. If you still have a safety concern, you can run the app from the source code by installing python in your environment. If you don't trust my code, just using online decoding tools :( .
Some discussions: [pyinstaller github issue](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed), [article](https://medium.com/@markhank/how-to-stop-your-python-programs-being-seen-as-malware-bfd7eb407a7), [stack over flow](https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg)

Finally, thanks to the people who read this and found this tool. This is just a small project that I build for learning python and Tkinter. I'm glad it could provide some help to the community. HoloCure is a very amazing game, hope everyone can enjoy it in various ways!
